### ISSUE TITLE
Non-linearity at output

### ISSUE THREAD

**Issue by yhl48** [pablomorales92/auNN#1]
From the code, it looks like you have added the activation function at the output, even for a regression problem. Am I mistaken, or is that supposed to be the case?

Thanks.

**Comment by pablomorales92** [comment]
Yes, that's supposed to be the case, see eq (1) in the ICLR paper. The activation is given by a GP so the output values are not restricted by using it.

**Comment by yhl48** [comment]
Thanks for the reply! I suppose in general not having the GP activation in the output would have minimal impact on the results?

> Yes, that's supposed to be the case, see eq (1) in the ICLR paper. The activation is given by a GP so the output values are not restricted by using it.

Another question is, you included variance in your calculation of the likelihood term in ELBO, I couldn't really wrap my head around that, could you clarify?

Thanks!

**Comment by pablomorales92** [comment]
Hey, as for your first question, I think it should not have a big impact if there have been some previous non-linear layers. As for the second one, the variance of the noise is estimated along with the rest of parameters within the gradient descent
